#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Dec 24, 2021 12:31:51 AM CAT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
py3 = True
import interface_support
import os.path

import main_menu
from info import info

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = Toplevel1 (root)
    interface_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    interface_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def show_menu(self, top=None):
        top.destroy()
        main_menu.vp_start_gui()
    def show_info(self, top=None):
        top.destroy()
        info.vp_start_gui()
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1080x720+245+67")
        top.minsize(120, 1)
        top.maxsize(1604, 881)
        top.resizable(0,  0)
        top.title("MathSolver")
        top.configure(background="#ffffff")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.259, rely=0.194, height=100, width=519)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        photo_location = os.path.join(prog_location,r"Assessts/interface_assists/Asset 2.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)
        self.Label1.configure(text='''Label''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.38, rely=0.458, height=84, width=260)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(borderwidth="0")
        self.Button1.configure(command=lambda: self.show_menu(top))
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(highlightthickness="0")
        photo_location = os.path.join(prog_location,r"Assessts/interface_assists/Asset 1.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.Button1.configure(image=_img1)
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="groove")
        self.Button1.configure(state='active')
        self.Button1.configure(text='''Button''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.565, rely=0.944, height=26, width=442)
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        photo_location = os.path.join(prog_location,r"Assessts/interface_assists/Asset 3.png")
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.Label2.configure(image=_img2)
        self.Label2.configure(text='''Label''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.037, rely=0.931, height=34, width=37)
        self.Button2.configure(activebackground="#ffffff")
        self.Button2.configure(activeforeground="#ffffff")
        self.Button2.configure(background="#ffffff")
        self.Button2.configure(borderwidth="0")
        self.Button2.configure(command=lambda: self.show_info(top))
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,r"Assessts/interface_assists/Asset 5.png")
        global _img3
        _img3 = tk.PhotoImage(file=photo_location)
        self.Button2.configure(image=_img3)
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Button''')

if __name__ == '__main__':
    vp_start_gui()





