#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Dec 26, 2021 02:20:41 AM CAT  platform: Windows NT

import sys
import numpy as np
from sympy.functions.elementary.complexes import im
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

from tkinter import messagebox
try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


from Determinant import determinant_support
sys.path.append("E:\MathProject")

import main_menu
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = Toplevel1 (root)
    determinant_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    determinant_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def back(self, top=None):
        top.destroy()
        main_menu.vp_start_gui()
    def show_info(self):
        messagebox.showinfo("Tutorial", "Enter a square matrix as following:\n(a11,a12,a21,a22.....)\n")
    def show_result(self, result):
        messagebox.showinfo("Result", str(result) + '\n')
    def calculate(self):
        if not self.Entry1.get():
            self.Label6.config(text = "Wrong Input")
            return
        s = self.Entry1.get()
        s = list(map(int, s.split(',')))
        n = len(s)

        if np.sqrt(n) * np.sqrt(n) != n:
            self.Label6.config(text = "Wrong Input")
            return
        mainL = list()
        for i in range(0, len(s), int(round(np.sqrt(n)))):
            mainL.append(s[i:i + int(round(np.sqrt(n)))])
            
        self.Label6.config(text = np.linalg.det(mainL))
        self.show_result(np.linalg.det(mainL))
        
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1080x720+240+103")
        top.minsize(120, 1)
        top.maxsize(1604, 881)
        top.resizable(0,  0)
        top.title("Determinant")
        top.configure(background="#ffffff")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.631, rely=0.272, height=301, width=250)
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        photo_location = os.path.join(prog_location,r"Assessts/calculators_assists/3.Determinant/Asset 3.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.139, rely=0.264, height=311, width=250)
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        photo_location = os.path.join(prog_location,r"Assessts/calculators_assists/3.Determinant/Asset 4.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.Label2.configure(image=_img1)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.235, rely=0.111, height=61, width=612)
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        photo_location = os.path.join(prog_location,r"Assessts/calculators_assists/3.Determinant/Asset 7.png")
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.Label3.configure(image=_img2)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.546, rely=0.931, height=31, width=441)
        self.Label4.configure(background="#ffffff")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        photo_location = os.path.join(prog_location,r"Assessts/calculators_assists/3.Determinant/Asset 2.png")
        global _img3
        _img3 = tk.PhotoImage(file=photo_location)
        self.Label4.configure(image=_img3)

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.385, rely=0.486, height=31, width=253)
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        photo_location = os.path.join(prog_location,r"Assessts/calculators_assists/3.Determinant/Asset 5.png")
        global _img4
        _img4 = tk.PhotoImage(file=photo_location)
        self.Label5.configure(image=_img4)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.046, rely=0.917, height=44, width=37)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(borderwidth="0")
        self.Button1.configure(command=self.show_info)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(highlightthickness="0")
        photo_location = os.path.join(prog_location,r"Assessts/calculators_assists/3.Determinant/Asset 1.png")
        global _img5
        _img5 = tk.PhotoImage(file=photo_location)
        self.Button1.configure(image=_img5)
        self.Button1.configure(pady="0")

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.88, rely=0.056, height=44, width=37)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#ffffff")
        self.Button2.configure(borderwidth="0")
        self.Button2.configure(command=lambda: self.back(top))
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(highlightthickness="0")
        photo_location = os.path.join(prog_location,r"Assessts/calculators_assists/3.Determinant/Asset 9.png")
        global _img6
        _img6 = tk.PhotoImage(file=photo_location)
        self.Button2.configure(image=_img6)
        self.Button2.configure(pady="0")

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.389, rely=0.764, height=84, width=247)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#ffffff")
        self.Button3.configure(borderwidth="0")
        self.Button3.configure(command=self.calculate)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(highlightthickness="0")
        photo_location = os.path.join(prog_location,r"Assessts/calculators_assists/3.Determinant/Asset 6.png")
        global _img7
        _img7 = tk.PhotoImage(file=photo_location)
        self.Button3.configure(image=_img7)
        self.Button3.configure(pady="0")

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.15, rely=0.365, height=220, relwidth=0.207)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3", justify='center')
        self.Entry1.configure(font="Arial")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Label6 = tk.Label(top)
        self.Label6.place(relx=0.644, rely=0.368, height=221, width=222)
        self.Label6.configure(background="#ffffff")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="Arial")
        self.Label6.configure(foreground="#000000")

if __name__ == '__main__':
    vp_start_gui()





